fullnameOverride: "prometheus-${cluster_name}"

prometheus:
  prometheusSpec:
    externalLabels:
      cluster: "${cluster_name}"

    retention: "${retention}"

    thanos:
      image: quay.io/thanos/thanos:v0.32.5

    thanosService:
      enabled: true

    thanosServiceMonitor:
      enabled: true

grafana:
  enabled: false